In [2]:
import numpy as np
from numpy import random
import numba as nb
import matplotlib.pyplot as plt

In [27]:
# test code
grid = np.array([[1,1,0],[0,1,0],[0,0,1]])
print(grid)
x=np.where(grid>0)
print(x)
axis = np.floor(2*random.rand(len(x[0]),2))
direc = 2*np.floor(2*random.rand(len(x[0]),2))-1
# print(axis,direc)

[[1 1 0]
 [0 1 0]
 [0 0 1]]
(array([0, 0, 1, 2]), array([0, 1, 1, 2]))


In [52]:
# sandpile

def topple_old(array,count):
     mask = np.copy(array)>=4
     frustration = np.sum(mask)
     count += frustration
     array[mask] += -4
     array[np.roll(mask,1,0)] += 1
     array[np.roll(mask,-1,0)] += 1
     array[np.roll(mask,1,1)] += 1
     array[np.roll(mask,-1,1)] += 1

     array[:,0] = 0
     array[:,-1] = 0
     array[0,:] = 0
     array[-1,:] = 0
     return count

def topple(array,count):
     mask = np.copy(array)>1
     N = np.shape(array)[0]
     frustration = np.sum(mask)
     count += frustration
     # create new array with update values to be added to array
     update_array = np.zeros(np.shape(array))
     # Subtract two from all active sites
     update_array[mask] += -2
     # Make tuple of indecies of active sites
     mask_indecies = np.where(mask)
     # for each active site, generate two random neighbours to gift unit
     axis = np.floor(2*random.rand(frustration,2))
     direction = 2*np.floor(2*random.rand(frustration,2))-1
     for active_num in range(frustration):
          i,j = mask_indecies[0][active_num],mask_indecies[1][active_num]
          for unit in range(2):
               if axis[active_num][unit] == 0:
                    update_array[(i+int(direction[active_num][unit]))%N,j] += 1
               elif axis[active_num][unit] == 1:
                    update_array[i,(j+int(direction[active_num][unit]))%N] += 1
     array += update_array
     array[:,0] = 0
     array[:,-1] = 0
     array[0,:] = 0
     array[-1,:] = 0
     return count

def sandpile(N,n_max):
     grid = np.zeros((N,N))
     grid = np.pad(grid,(1,1),constant_values=(0,0))
     avalanche_size = []
 #    indecies = random.randint(1,N+1,size = (n_max,2))
     indecies_for_adding = np.floor(N*random.rand())
     for k in range(n_max):
          if np.any(grid>1):
               count = 0
               while np.any(grid>1):
                    count = topple(grid,count)
               avalanche_size.append(count)
          else:
               avalanche_size.append(0)
          grid[indecies_for_adding[k,0],indecies_for_adding[k,1]] += 1
     return avalanche_size

In [121]:
grid = np.zeros((5,5))
grid[1,1]=2
print(grid)
topple(grid,0)
print(grid)

[[0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
